name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v7
        with:
          java-version: 1.8
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Checking your code format
        run: csbt scalafmtCheckAll
      - name: Run tests 0.6
        run: |
          SCALAJS_VERSION=0.6.33 csbt clean +apiJVM/test +apiJS/test +apiJVM/publishLocal sbt_locales/publishLocal
          SCALAJS_VERSION=0.6.33 csbt sbt_locales/scripted
      - name: Run tests
        run: |
          csbt clean +apiJVM/test +apiJS/test +apiJVM/publishLocal
          csbt sbt_locales/scripted
